= 5. Advanced Exercises

If you found the proposed exercises in this workshop too straightforward or relied too heavily on copy-paste steps, you're in luck. These advanced exercises require you to work independently to achieve the desired outcomes.

== 5.1 Certificates with cert-manager

By now, you may have noticed a significant difference between the `argo-hub` cluster and the `sno-XX` clusters regarding certificates. The `argo-hub` cluster uses certificates with a proper Certificate Authority (CA) chain issued by Let's Encrypt, while the `sno-XX` clusters rely on default self-signed certificates from the installation process. This approach is not suitable for production environments, as it can raise concerns about potential Man-in-the-Middle (MitM) attacks.

In this exercise, you will explore the benefits of using the cert-manager operator. You will configure it to automatically generate and manage two types of certificates, integrating them into your OpenShift GitOps configuration:

* **API Certificate**: This certificate will provide secure access to your cluster's API, ensuring that all communication between clients and the API server is encrypted and authenticated. This is crucial for maintaining the integrity and confidentiality of cluster operations.

* **Ingress Certificate**: This certificate will be used for securing ingress traffic to your cluster. It will be a wildcard certificate, meaning it can secure multiple subdomains under a single domain (e.g., *.example.com). This allows you to manage a single certificate for multiple services or applications hosted within your cluster, simplifying certificate management and ensuring that all incoming traffic is encrypted.


**Steps to Complete**

1. Install cert-manager: Deploy the cert-manager operator in your cluster.
2. Configure Certificate Issuers: Set up certificate issuers for Let's Encrypt or another preferred CA.
3. Create Certificate Requests: Define certificate requests for both the API and Ingress certificates.
4. Integrate with OpenShift GitOps: Configure your GitOps setup to use these certificates for secure API and ingress traffic.

This exercise will help you understand how to automate certificate management in a production-ready environment, enhancing the security and reliability of your OpenShift cluster.

If you want to look for information, I recommend you to get inspired by the following sources of information:

* Documentation https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/security_and_compliance/cert-manager-operator-for-red-hat-openshift#cert-manager-operator-about[cert-manager Operator for Red Hat OpenShift].
* GitHub repository https://github.com/alvarolop/ocp-secured-integration?tab=readme-ov-file#2-cert-manager[alvarolop/ocp-secured-integration].

IMPORTANT: Please, try to do some research before keep reading!!

Ok, maybe it was too difficult, as I didn't give you any code example, so let's try to split this task in small pieces.


=== Hint 1: The operator

As there could be some version dependencies in the cluster and you only want to install the operator once, but use it from several application or teams, it is a common practice to centralize the installation of operators in a different application. That is the reason why we have the `sno-XX-operators` application. 

Please, add the cert-manager operator to the Helm Chart and make sure that the operator is installed after syncing the app again!!


=== Hint 2: The cert-manager files


Once you have the operator installed, you will need to add several configuration files to the `helm-infra-gitops-workshop`. Best practice is to create a new ArgoCD application, a new folder and a new values file. So let's do it!!

* The folder should be named `cert-manager` and contain the structure of a Helm Chart. Inside the `templates` folder you will have the files from the next hints. Yo can keep it empty now.
* Create a `values-cert-manager.yaml` file with a boilerplate content like:
+
[source, yaml]
----
cert-manager:
  enabled: true
----
+
* Push it
* Create an ArgoCD application pointing to that path and check that the Application is Healthy, despite is doesn't create any new resource on the cluster.


=== Hint 3: The cert-manager configuration

Now, it's time to actually add the cert-manager configuration, which can be split in a few steps:

1. Use the **CredentialsRequest** from the OpenShift Cloud Credential Operator to request specific tailored AWS credentials to list DNS records:
+
[.console-input]
[source, yaml, subs="+macros,+attributes"]
----
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager
  namespace: openshift-cloud-credential-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-10"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - "route53:GetChange"
      effect: Allow
      resource: "arn:aws:route53:::change/*"
    - action:
      - "route53:ChangeResourceRecordSets"
      - "route53:ListResourceRecordSets"
      effect: Allow
      resource: "arn:aws:route53:::hostedzone/*"
    - action:
      - "route53:ListHostedZonesByName"
      effect: Allow
      resource: "*"
  secretRef:
    name: aws-creds
    namespace: cert-manager
  serviceAccountNames:
  - cert-manager
----
+
2. Create a **CertManager** instance to initialize the operator configuration:
+
[.console-input]
[source, yaml, subs="+macros,+attributes"]
----
apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "05"
spec:
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  unsupportedConfigOverrides: null
  controllerConfig:                                
    overrideArgs:
      - '--dns01-recursive-nameservers-only'       
      - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'
      - '--enable-certificate-owner-ref' # Deleting a TLS secret automatically upon Certificate removal
----
+
3. Create a **ClusterIssuer**, which will provide the configuration to the Certificate Authority:
+
[.console-input]
[source, yaml, subs="+macros,+attributes"]
----
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "05"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # email: mail@example.com # Replace with your email
    # skipTLSVerify: true
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        route53:
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
          region: eu-west-1
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key
----

=== Hint 4: The Certificates

Create the **Certificate** CR to issue a certificate against a ClusterIssuer:

[.console-input]
[source, yaml, subs="+macros,+attributes"]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocp-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  isCA: false
  commonName: "api.{{ .Values.clusterDomain }}" 
  dnsNames:
  - "api.{{ .Values.clusterDomain }}" 
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: api-certs
----


We hope you enjoyed this extra DIY section, where we provided a less structured path for you to explore and adapt your GitOps repository in a way that best suits your needs. 

Thank you for joining us, and we look forward to seeing you in our next workshop! 👋👋
